name: Release Image
on:
  push:
    branches:
      - main
      - release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SERVICE_NAME: graphql-playground
  DOCKERHUB_REPO: ${{ vars.DOCKERHUB_ORG }}/${{ github.event.repository.name }}

jobs:
  build:
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ${{ matrix.arch }}
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          docker context create ci
          docker context use ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master
          version: v0.10.4
          endpoint: ci

      - name: Setup variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "endpoint=api.holaplex.com" >> $GITHUB_OUTPUT
          else
            echo "endpoint=api.holaplex.dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push ${{ github.event.repository.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            API_ENDPOINT=${{ steps.vars.outputs.endpoint }}
          provenance: false
          platforms: linux/${{ matrix.arch }}
          tags: ${{ vars.DOCKERHUB_ORG }}/${{ github.event.repository.name }}:latest-${{ matrix.arch }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  finalize:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Merge service image tags
        uses: Noelware/docker-manifest-action@master
        with:
          inputs: ${{ env.DOCKERHUB_REPO }}:latest,${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          images: ${{ env.DOCKERHUB_REPO }}:latest-amd64,${{ env.DOCKERHUB_REPO }}:latest-arm64
          push: true

      - name: Setup variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=stage" >> $GITHUB_OUTPUT
          fi

      - name: Invoke workflow in hub-kubes repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          ref: main
          token: ${{ secrets.ACTIONS_TOKEN }}
          workflow: release.yml
          repo: holaplex/hub-kubes
          inputs: '{ "service": "${{ env.SERVICE_NAME }}", "environment": "${{ steps.vars.outputs.environment }}", "commit_hash": "${{ github.sha }}"}'
